#!/usr/bin/env bash
# install nginx
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
FILE="/etc/nginx/sites-available/default"
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "37i\ $REDIRECT" "$FILE"
service nginx restart
